ARG CMDPROXY_TAG
ARG OPAM_TAG
ARG BAP_VERSION

FROM cmdproxy.rs:${CMDPROXY_TAG} AS cmdproxy_builder

RUN cp `which cmdproxy` /

FROM bap/${OPAM_TAG}:${BAP_VERSION}

WORKDIR /home/cmdproxy

# setup ocaml environment
RUN eval `opam env`

# prepare configuration command-palette
COPY --from=cmdproxy_builder /cmdproxy ./
RUN echo "\n\
bap: /home/opam/.opam/4.13/bin/bap" \
    >> ./command-palette.yaml

ENV CMDPROXY_COMMAND_PALETTE=/home/cmdproxy/command-palette.yaml

ENTRYPOINT ["./cmdproxy"]
